### ISSUE TITLE
Why use `NSLocalizedFailureReason` for the title and not `NSLocalizedDescription`?

### ISSUE THREAD

**Issue by JoachimK** [Hotel-Reservation-Service/HRSCustomErrorHandling#8]
Something I have meant to ask you for a long time: Why did you choose to use `NSLocalizedFailureReasonKey` for the alerts title by default, why not `NSLocalizedDescriptionKey`?

As far as I can tell this is what the NSAlertPanel on OS X does:

* Use `localizedDescription` for the title
* Use `localizedRecoverySuggestion` as the informative text
* Use `localizedRecoveryOptions` for the button titles
* Ignore `localizedFailureReason` *(Although I would have sworn it would be shown in a paragraph before the recovery suggestion, but apparently it's not)*

So you are almost doing the same thing, but using `failureReason` differently. The added advantage of using the `localizedDescription` would be that many errors already have it set because it is auto-generated from error information if not provided in the userInfo dictionary.

Is that something that you could (and would be willing to) change (considering the library is still in it's `0.x` stage)? It's the main reason preventing me from using it more often and I would be happy to implement it. ^^

**Comment by michaelochs** [comment]
The problem with using the `localizedDescription` is that you still can't simply present this error as you would still require an `HRSErrorAttempter` in order to add buttons to the dialog. What we do is, implement `willPresentError:` in our `AppDelegate` and adjust the error accordingly for all errors that we have not customized yet.

The idea was that if we need to customize the error anyway, if you want to see the often very cryptic `localizedDescription` in your error UI, it could as well be an explicit action.

Let me know what you think about this approach and why it does not work for you.

**Comment by JoachimK** [comment]
My problem with using the failure reason for the title is twofold, I guess:

**Inappropriate Usage** : The `localizedFailureReason` property has been define by Apple but was not clearly meant to be displayed in an alert's (or other error messages) title. Although the usage recommendation in the documentation is rather unclear ("A string containing the localized explanation of the reason for the error.") Apple could later decide to create a default error display and use the failure reason somewhere in that UI. In that cases, errors created with HRSCustomErrorHandling in mind might not be compatible with that new (and hypothetical, yes ^^) Apple way of doing things. In the same way, another error handling framework might come along and use the `localizedFailureReason` property in a completely different way. 
**Inconsistent with Mac OS X**: Mac OS X already has a default error display, the `NSAlert`. It uses the `localizedDescription` for the title of the alert. Although, I don't think it's a great naming choice and many automatically generated `localizedDescription`s are not great alert titles, using the `localizedDescription` would at least be consistent with Mac OS X. It would also mean that almost all errors get at least a somewhat sensible default display by just adding an `HRSRecoveryAttempter` with a cancel button to it. Currently, for an unknown error you would either use "Unknown error" or similar as failure reason to be displayed in the title, or copy over the `localizedDescription`. In that case why not use the `localizedDescription` directly?

You also don't need the `localizedFailureReason` to identify not-yet-customized errors in the `AppDelegate` since those can be identified by a missing recovery attempter.


In summary, this library should in my opinion
* either use `localizedDescription` to be consistent with Mac OS X
* or introduce a new user-info key for the error dictionary like `HRSLocalizedTitleKey` to save the title for an alert. This way, you would be not (ab)use an already existing property AND it would be much clearer what the value for that key is for and how it is meant to be used/displayed.


In addition, I think the default error display should display the error `localizedFailureReason` in the body of the alert in addition to the recover suggestion, but that's a different topic. 


In my mind, an ideal error message tells me, the user
* What went wrong?
* Why did it go wrong? 
* What can I do about it? What should I do now?

Using an example I was playing around with, it could look like this:
![error message](https://cloud.githubusercontent.com/assets/3660652/10952900/4a3f66a6-8345-11e5-8fe7-085432c418f3.png)

Note, that the title answers the "what", the body answers the "why" and "what now" and the buttons also answer the "what now". However, a "failure reason" seems like it answers the "why" not the "what" so it does not seem appropriate to be displayed in the title, for me.

**Comment by michaelochs** [comment]
Thanks for your clarification on this. I'll bring this into the team here and discuss this issue with them. I do understand your reasoning.

Can you confirm that the screenshot you posted is the default implementation on OS X and that it shows the `localizedDescription`, `localizedFailureReason`, and `localizedRecoverySuggestion`? Would you say that using the `localizedDescription` as the title and `localizedFailureReason`\n\n`localizedRecoverySuggestion` as an alert's message?

**Comment by JoachimK** [comment]
The screenshot is almost the the default implementation on OS X. I did change it slightly.

For some reason, OS X completely ignores the failure reason in the NSAlert and only uses `localizedDescription` and `localizedRecoverySuggestion` and `localizedRecoverOptions`, and I don't know why. I have used it years ago and before trying it in an example project again, I was sure the `localizedFailureReason` would also be part of the alert. Maybe it was changed in some of the newer Mac OS X release.

However, the current implementation of `NSAlert` will use:
* `localizedDescription` for the title
* `localizedRecoverySuggestion` for the body text
* `localizedRecoveryOptions` for the buttons

Since I thought the failure reason should be included I did the following to achieve the screenshot above:

```objc
NSError *error = [NSError errorWithDomain:@"MyCoolDomain" code:1 userInfo:@{
                          NSLocalizedDescriptionKey: @"Could Not Post Message",
                          NSLocalizedFailureReasonErrorKey: @"We could not reach the XING server. Your internet connection seems to be offline.",
                          NSLocalizedRecoverySuggestionErrorKey: @"You may try again when you are online again.",
                          NSLocalizedRecoveryOptionsErrorKey: @[@"Try again", @"Cancel"]
                      }];
    NSAlert *alert = [NSAlert alertWithError:error];
    alert.informativeText = [error.localizedFailureReason stringByAppendingFormat:@"\n\n%@", alert.informativeText];
    [alert beginSheetModalForWindow:self.view.window completionHandler:^(NSModalResponse returnCode) {
    }];
```

**Comment by michaelochs** [comment]
I talked about this with the team and we decided to make this change in the following form:

- The `localizedDescription` will be used as the alert's title
- The `localizedRecoverySuggestion` will be used as the alert's body
- If no `HRSRecoveryAttempter` is available on an error, we will add a simple `OK` recovery suggestion that simply dismisses the error when selecting it.
- The `localizedFailureReason` will be added to the alert body if you opt in to this feature. (Where this opt in will be is still to be discussed).

Would this implementation fix this issue for you?

**Comment by JoachimK** [comment]
Yes, that would definitely fix the issue for me and make me very happy! :-)
I also think it's a great idea to have an opt-in for including the `localizedFailureReason` in the alert's body.

**Comment by michaelochs** [comment]
@JoachimK I am currently working on this implementation. Do you have a nice idea about how to provide the 'ok' text in case no recovery attempter is available? The most elegant way I know is the project from @McZonk (https://github.com/McZonk/UIKitPlusLocalization/blob/master/NSBundle%2BUIPStandardLocalizations.m) but it requires to 'guess' the location of the UIKit framework correctly (https://github.com/McZonk/UIKitPlus/blob/master/NSBundle%2BUIPUIKitBundle.m).

**Comment by michaelochs** [comment]
@JoachimK please have a look at the PR

**Comment by michaelochs** [comment]
I consider this as fixed, with the only difference that currently the option to show both, the `localizedFailureReason` and the `localizedRecoverySuggestion` within the body is not supported.

**Comment by JoachimK** [comment]
Thanks a lot, looks good!

I hope I can get my team to use it soon :-)
